version: '3.8'

services:
  # Base de données PostgreSQL avec PostGIS
  postgres:
    image: postgis/postgis:15-3.3
    container_name: lumina-postgres
    environment:
      POSTGRES_DB: lumina_africa
      POSTGRES_USER: lumina_user
      POSTGRES_PASSWORD: lumina_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lumina-network

  # Redis pour le cache
  redis:
    image: redis:7-alpine
    container_name: lumina-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - lumina-network

  # Elasticsearch pour la recherche
  elasticsearch:
    image: elasticsearch:7.17.9
    container_name: lumina-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - lumina-network

  # Backend NestJS
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lumina-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://lumina_user:lumina_password@postgres:5432/lumina_africa
      - REDIS_URL=redis://redis:6379
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - postgres
      - redis
      - elasticsearch
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - lumina-network

  # Frontend Next.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lumina-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - lumina-network

volumes:
  postgres_data:
  redis_data:
  elasticsearch_data:

networks:
  lumina-network:
    driver: bridge

