#!/bin/bash

# Script de déploiement alternatif pour Vercel
echo "🚀 Déploiement Vercel Alternatif"
echo "================================="

echo "📋 Problème identifié :"
echo "Le compte Git 'macmiui@Macs-Mac-mini.local' n'a pas accès à l'équipe 'enollafritz' sur Vercel"
echo ""

echo "🔧 Solutions possibles :"
echo ""
echo "1. **Changer le compte Git local :**"
echo "   git config --global user.email 'votre-email@vercel.com'"
echo "   git config --global user.name 'Votre Nom'"
echo ""
echo "2. **Créer un nouveau projet Vercel :**"
echo "   - Allez sur https://vercel.com/dashboard"
echo "   - Cliquez sur 'New Project'"
echo "   - Importez le repository GitHub"
echo "   - Configurez les variables d'environnement"
echo ""
echo "3. **Utiliser le dashboard Vercel :**"
echo "   - Connectez le repository GitHub directement"
echo "   - Configurez le build command : 'npm run vercel-build'"
echo "   - Configurez le output directory : 'dist'"
echo ""

echo "📊 Configuration recommandée pour le dashboard Vercel :"
echo ""
echo "**Build Settings :**"
echo "- Framework Preset: Other"
echo "- Build Command: npm run vercel-build"
echo "- Output Directory: dist"
echo "- Install Command: npm install"
echo ""
echo "**Environment Variables :**"
echo "- NODE_ENV=production"
echo "- DATABASE_URL=postgresql://postgres.baoywgzpmndrbiagiczs:Eliefritz97@aws-1-ca-central-1.pooler.supabase.com:6543/postgres"
echo "- NEXT_PUBLIC_SUPABASE_URL=https://baoywgzpmndrbiagiczs.supabase.co"
echo "- NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
echo "- FRONTEND_URL=https://lumina-africa-frontend.vercel.app"
echo ""

echo "🌐 URLs utiles :"
echo "- Dashboard Vercel: https://vercel.com/dashboard"
echo "- Repository GitHub: https://github.com/ElieFritz/Lumina"
echo ""

echo "✅ Instructions complètes dans vercel-guide.md"
