#!/bin/bash

echo "🔍 Diagnostic Vercel - Problème de Routing"
echo "=========================================="

echo "📋 Problème identifié :"
echo "Vercel retourne 'The page could not be found' pour toutes les routes"
echo "Cela indique un problème de configuration ou de build"
echo ""

echo "🔧 Solutions à essayer :"
echo ""
echo "1. **Vérifiez les logs de build dans Vercel :**"
echo "   - Allez sur https://vercel.com/dashboard"
echo "   - Sélectionnez votre projet"
echo "   - Onglet 'Deployments'"
echo "   - Cliquez sur le dernier déploiement"
echo "   - Vérifiez les logs de build"
echo ""

echo "2. **Vérifiez la configuration du projet :**"
echo "   - Root Directory: backend"
echo "   - Build Command: npm run build"
echo "   - Output Directory: dist"
echo "   - Install Command: npm install"
echo ""

echo "3. **Variables d'environnement requises :**"
echo "   NODE_ENV=production"
echo "   DATABASE_URL=postgresql://postgres.baoywgzpmndrbiagiczs:Eliefritz97@aws-1-ca-central-1.pooler.supabase.com:6543/postgres"
echo "   NEXT_PUBLIC_SUPABASE_URL=https://baoywgzpmndrbiagiczs.supabase.co"
echo "   NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
echo "   FRONTEND_URL=https://lumina-africa-frontend.vercel.app"
echo ""

echo "4. **Solution alternative - Créer un nouveau projet :**"
echo "   - Supprimez le projet actuel"
echo "   - Créez un nouveau projet"
echo "   - Importez le repository"
echo "   - Configurez avec les paramètres ci-dessus"
echo ""

echo "5. **Test de l'API localement :**"
echo "   cd /Users/macmiui/lumina/Lumina/backend"
echo "   npm run build"
echo "   node dist/main.js"
echo "   curl http://localhost:10000/api/health"
echo ""

echo "📊 Configuration actuelle :"
echo "- vercel.json : ✅ Configuré"
echo "- api/index.js : ✅ Handler Express + NestJS"
echo "- dist/ : ✅ Fichiers compilés présents"
echo "- package.json : ✅ Dépendances installées"
echo ""

echo "🎯 Prochaines étapes :"
echo "1. Vérifiez les logs Vercel"
echo "2. Si nécessaire, créez un nouveau projet"
echo "3. Testez l'API localement"
echo "4. Redéployez avec la bonne configuration"
echo ""

echo "🔗 Liens utiles :"
echo "- Dashboard Vercel: https://vercel.com/dashboard"
echo "- Repository: https://github.com/ElieFritz/Lumina"
echo "- API locale: http://localhost:10000/api/health"
