#!/bin/bash

# Script de déploiement manuel pour VPS Contabo
# Usage: ./scripts/deploy-manual.sh

echo "🚀 Déploiement Manuel de Lumina Africa sur VPS Contabo"
echo "======================================================"
echo ""

# Configuration
VPS_HOST="31.220.90.241"
VPS_USER="root"
APP_DIR="/opt/lumina"

echo "📋 Instructions de déploiement :"
echo "================================"
echo ""
echo "1. Connectez-vous à votre VPS :"
echo "   ssh $VPS_USER@$VPS_HOST"
echo ""
echo "2. Une fois connecté, exécutez ces commandes :"
echo ""
echo "   # Préparation du serveur"
echo "   apt update && apt upgrade -y"
echo "   apt install -y git curl wget unzip"
echo "   mkdir -p $APP_DIR"
echo "   mkdir -p /opt/lumina-backup"
echo "   ufw allow 22/tcp"
echo "   ufw allow 80/tcp"
echo "   ufw allow 443/tcp"
echo "   ufw --force enable"
echo ""
echo "3. Cloner le repository :"
echo "   cd /opt"
echo "   git clone https://github.com/ElieFritz/Lumina.git"
echo "   cd Lumina"
echo ""
echo "4. Configuration de l'environnement :"
echo "   cp env.production .env"
echo "   mkdir -p logs/nginx"
echo "   mkdir -p nginx/ssl"
echo ""
echo "5. Éditer le fichier .env (IMPORTANT !) :"
echo "   nano .env"
echo ""
echo "   Configurez au minimum :"
echo "   - MONGODB_URI (votre chaîne de connexion MongoDB Atlas)"
echo "   - JWT_SECRET (une clé secrète forte)"
echo "   - REDIS_PASSWORD (mot de passe pour Redis)"
echo "   - FRONTEND_URL (URL de votre frontend Vercel)"
echo ""
echo "6. Déploiement avec Docker :"
echo "   docker-compose -f docker-compose.prod.yml down || true"
echo "   docker image prune -f"
echo "   docker-compose -f docker-compose.prod.yml up -d --build"
echo "   sleep 30"
echo ""
echo "7. Vérification :"
echo "   docker-compose -f docker-compose.prod.yml ps"
echo "   docker-compose -f docker-compose.prod.yml logs backend"
echo "   curl http://localhost:3001/health"
echo ""
echo "🌐 Une fois déployé, votre backend sera accessible sur :"
echo "   - http://$VPS_HOST:3001"
echo "   - http://$VPS_HOST:3001/health"
echo ""
echo "📊 Commandes utiles pour la maintenance :"
echo "   - Logs en temps réel : docker-compose -f docker-compose.prod.yml logs -f"
echo "   - Redémarrer : docker-compose -f docker-compose.prod.yml restart"
echo "   - Arrêter : docker-compose -f docker-compose.prod.yml down"
echo ""
echo "🔒 Prochaines étapes :"
echo "   1. Configurer MongoDB Atlas"
echo "   2. Configurer un certificat SSL"
echo "   3. Configurer un nom de domaine"
echo "   4. Tester l'API complète"
echo ""
echo "Voulez-vous que je vous aide avec une étape spécifique ?"

